# Generated by Django 3.2.6 on 2021-11-16 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('cid', models.TextField(primary_key=True, serialize=False)),
                ('cname', models.TextField()),
                ('cowner', models.TextField()),
                ('cyield', models.FloatField()),
                ('pe_ratio', models.FloatField()),
                ('industry_type', models.TextField()),
            ],
            options={
                'db_table': 'stock"."company',
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('iname', models.TextField()),
                ('acct_no', models.TextField(unique=True)),
                ('pwd', models.TextField()),
                ('phone', models.TextField()),
            ],
            options={
                'db_table': 'stock"."investor',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('budget', models.FloatField()),
                ('strategy_type', models.CharField(max_length=1)),
                ('creator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.investor')),
            ],
            options={
                'db_table': 'stock"."strategy',
            },
        ),
        migrations.CreateModel(
            name='EMA',
            fields=[
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.strategy')),
                ('company_id', models.TextField()),
                ('fast_line', models.FloatField()),
                ('slow_line', models.FloatField()),
                ('loss', models.FloatField()),
                ('profit', models.FloatField()),
            ],
            options={
                'db_table': 'stock"."ema',
            },
        ),
        migrations.CreateModel(
            name='KD',
            fields=[
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.strategy')),
                ('company_id', models.TextField()),
                ('threshold', models.FloatField()),
                ('kd_length', models.FloatField()),
                ('loss', models.FloatField()),
                ('profit', models.FloatField()),
            ],
            options={
                'db_table': 'stock"."kd',
            },
        ),
        migrations.CreateModel(
            name='MACD',
            fields=[
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.strategy')),
                ('company_id', models.TextField()),
                ('fast_line', models.FloatField()),
                ('slow_line', models.FloatField()),
                ('loss', models.FloatField()),
                ('profit', models.FloatField()),
            ],
            options={
                'db_table': 'stock"."macd',
            },
        ),
        migrations.CreateModel(
            name='RSI',
            fields=[
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.strategy')),
                ('company_id', models.TextField()),
                ('threshold', models.FloatField()),
                ('rsi_length', models.FloatField()),
                ('loss', models.FloatField()),
                ('profit', models.FloatField()),
            ],
            options={
                'db_table': 'stock"."rsi',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddate', models.DateField()),
                ('volume', models.TextField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
            ],
            options={
                'db_table': 'stock"."deal',
                'unique_together': {('company_id', 'ddate')},
            },
        ),
    ]
