# Generated by Django 3.2.6 on 2021-11-14 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Cid', models.TextField(primary_key=True, serialize=False)),
                ('CName', models.TextField()),
                ('COwner', models.TextField()),
                ('Yield', models.FloatField()),
                ('PE_Ratio', models.FloatField()),
                ('Industry_type', models.TextField()),
            ],
            options={
                'db_table': 'Stock"."company',
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('Iid', models.AutoField(primary_key=True, serialize=False)),
                ('IName', models.TextField()),
                ('Acct_no', models.TextField(unique=True)),
                ('Pwd', models.TextField()),
                ('Phone', models.TextField()),
            ],
            options={
                'db_table': 'Stock"."investor',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('Sid', models.AutoField(primary_key=True, serialize=False)),
                ('Budget', models.FloatField()),
                ('Strategy_type', models.CharField(max_length=1)),
                ('Creator_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.investor')),
            ],
            options={
                'db_table': 'Stock"."strategy',
            },
        ),
        migrations.CreateModel(
            name='EMA',
            fields=[
                ('Sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.strategy')),
                ('Company_id', models.TextField()),
                ('Fast_line', models.FloatField()),
                ('Slow_line', models.FloatField()),
                ('Loss', models.FloatField()),
                ('Profit', models.FloatField()),
            ],
            options={
                'db_table': 'Stock"."ema',
            },
        ),
        migrations.CreateModel(
            name='KD',
            fields=[
                ('Sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.strategy')),
                ('Company_id', models.TextField()),
                ('Threshold', models.FloatField()),
                ('KD_Length', models.FloatField()),
                ('Loss', models.FloatField()),
                ('Profit', models.FloatField()),
            ],
            options={
                'db_table': 'Stock"."kd',
            },
        ),
        migrations.CreateModel(
            name='MACD',
            fields=[
                ('Sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.strategy')),
                ('Company_id', models.TextField()),
                ('Fast_line', models.FloatField()),
                ('Slow_line', models.FloatField()),
                ('Loss', models.FloatField()),
                ('Profit', models.FloatField()),
            ],
            options={
                'db_table': 'Stock"."macd',
            },
        ),
        migrations.CreateModel(
            name='RSI',
            fields=[
                ('Sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.strategy')),
                ('Company_id', models.TextField()),
                ('Threshold', models.FloatField()),
                ('RSI_Length', models.FloatField()),
                ('Loss', models.FloatField()),
                ('Profit', models.FloatField()),
            ],
            options={
                'db_table': 'Stock"."rsi',
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ddate', models.DateField()),
                ('Volume', models.TextField()),
                ('High', models.FloatField()),
                ('Low', models.FloatField()),
                ('Company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.company')),
            ],
            options={
                'db_table': 'Stock"."deal',
                'unique_together': {('Company_id', 'Ddate')},
            },
        ),
    ]
